name: PR Template Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PR Template
        uses: actions/checkout@v2
      - name: Check PR Template
        run: |
          if [[ ! -f "${GITHUB_WORKSPACE}/.github/pull_request_template/template.md" ]]; then
            echo "Please add a PR template."
            exit 1
          fi
